name: fanitek_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.7.0
  dio: ^5.4.3+1
  firebase_core: ^2.10.0
  firebase_auth: ^4.16.0
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  pull_to_refresh_flutter3: ^2.0.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
